#! /usr/bin/env python
#
# Support module generated by PAGE version 4.8.6
# In conjunction with Tcl version 8.6
#    Nov 26, 2016 06:15:06 PM


import sys
from copy import deepcopy
from .utils.table_input import TableInput
from .model import NodeCpdModel, NodeContinuousInterval

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global var_lst_nodes
    var_lst_nodes = StringVar()

    global var_lst_risks
    var_lst_risks = StringVar()

    global var_notif
    var_notif = StringVar()


def cmd_cpd_apply_label():
    print('duration3_support.cmd_choices_apply')
    sys.stdout.flush()
    txt_str = w.txt_cpd_labels.get(1.0, END)
    labels = [x for x in txt_str.split() if x]

    node = get_current_node()
    node.labels = labels

    redraw_data()


def cmd_cpd_apply_npt():
    print('duration3_support.cmd_data_apply')
    sys.stdout.flush()
    data = w.data_cpd_table.export_data()
    print('Apply data %s' %str(data))
    node = get_current_node()
    node.data = data


def cmd_dist_apply():
    print('duration3_support.cmd_dist_apply')
    sys.stdout.flush()
    data = w.data_dist_table.export_data()
    print('Apply data %s' %str(data))
    node = get_current_node()
    node.data = data


def cmd_help():
    print('duration3_support.cmd_help')
    sys.stdout.flush()

def cmd_ok():
    print('duration3_support.cmd_ok')
    sys.stdout.flush()
    w.callback(w.orig_duration_model, w.duration_model)

def cmd_apply():
    pass

def cmd_quit():
    print('duration3_support.cmd_quit')
    sys.stdout.flush()
    w.callback(w.orig_duration_model, None)

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

    w.orig_duration_model = kwargs['duration_model']
    w.duration_model = deepcopy(w.orig_duration_model)
    w.callback = kwargs['callback']

    init_list()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


def init_list():
    global w

    app = w

    # list risk
    lst_risks = app.lst_risks
    lst_risks.configure(values=w.duration_model.element_names_label)
    lst_risks.set(w.duration_model.element_names_label[0])
    w.lst_nodes_cur_select = 0

    on_lst_risks_select(None)

def on_lst_risks_select(event):

    # print(w.lst_risks.get())
    str_select = w.lst_risks.get()
    if str_select == w.lst_risks_cur_select:
        return

    # fill lst_nodes
    w.lst_nodes.delete(0, END)
    element = w.duration_model.get_element(w.duration_model.get_element_label_index(str_select))
    node_names = element.nodes_name_label
    for s in node_names:
        w.lst_nodes.insert(END, s)
    w.lst_nodes.select_set(0,0)
    w.lst_risks_cur_select = str_select
    redraw_data()

def on_lst_nodes_select(event):
    if w.lst_nodes.curselection():
        index = w.lst_nodes.curselection()[0]
        print('Lst nodes select %s' % index)
        if index == w.lst_nodes_cur_select:
            return
        w.lst_nodes_cur_select = index
        redraw_data()

def redraw_data():
    print('redaw data')
    node = get_current_node()
    if hasattr(node, 'get_type_string'):
        type = node.get_type_string()
        w.lb_type.configure(text='Type: %s' % type)
    else:
        w.lb_type.configure(text='')

    if isinstance(node, NodeCpdModel):
        switch_tab(0)
        # render labels
        w.txt_cpd_labels.config(state=NORMAL)
        w.txt_cpd_labels.delete(1.0, END)
        str_labels = '\n'.join(node.labels)
        w.txt_cpd_labels.insert(END, str_labels)

        if node.lock_labels:
            w.txt_cpd_labels.config(state=DISABLED)
            w.btn_cpd_apply_labels.config(state=DISABLED)
        else:
            w.txt_cpd_labels.config(state=NORMAL)
            w.btn_cpd_apply_labels.config(state=NORMAL)

        # render data
        for widget in w.frm_cpd_npt.winfo_children():
            widget.destroy()

        rows = node.labels
        columns = node.get_table_labels()
        data = node.data
        w.data_cpd_table = TableInput(w.frm_cpd_npt,rows, columns, data)
    elif isinstance(node, NodeContinuousInterval):
        switch_tab(1)
        columns = node.get_columns_label()
        rows = node.get_rows_label()

        # render data
        for widget in w.frm_distribution_table.winfo_children():
            widget.destroy()

        data = node.data
        w.data_dist_table = TableInput(w.frm_distribution_table,rows, columns, data)

def switch_tab(index):
    tabs = (w.frm_cpd_content, w.frm_distribution)
    for i in range(len(tabs)):
        if i!=index:
            tabs[i].place_forget()
    tabs[index].place(tabs[index].pi)

def get_current_node():
    element = w.duration_model.get_element(w.duration_model.get_element_label_index(w.lst_risks_cur_select))
    node = element.get_node_by_id(w.lst_nodes_cur_select)
    return node

if __name__ == '__main__':
    import from_duration

    from_duration.vp_start_gui()
