#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.8.6
# In conjunction with Tcl version 8.6
#    Nov 26, 2016 04:44:21 PM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

from . import duration_support
# import duration_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    duration_support.set_Tk_var()
    top = Duration_Model (root)
    duration_support.init(root, top)
    root.mainloop()

w = None
def create_Duration_Model(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    duration_support.set_Tk_var()
    top = Duration_Model (w)
    duration_support.init(w, top, *args, **kwargs)

    # duration_support.parents = (root, w)
    # duration_support.form = top

    return (w, top)

def destroy_Duration_Model():
    global w
    w.destroy()
    w = None


class Duration_Model:
    lst_risks_cur_select = ""
    lst_nodes_cur_select = -1
    duration_model = None
    ori_duration_model = None
    data_table = None
    callback = None

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        self._bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        self._fgcolor = '#000000'  # X11 color: 'black'
        self._compcolor = '#d9d9d9' # X11 color: 'gray85'
        self._ana1color = '#d9d9d9' # X11 color: 'gray85' 
        self._ana2color = '#d9d9d9' # X11 color: 'gray85' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=self._bgcolor)
        self.style.configure('.',foreground=self._fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', self._compcolor), ('active',self._ana2color)])

        top.geometry("787x409+315+85")
        top.title("Duration Model")


        self.lst_nodes = Listbox(top)
        self.lst_nodes.place(relx=0.08, rely=0.15, relheight=0.5, relwidth=0.18)
        self.lst_nodes.configure(background="white")
        self.lst_nodes.configure(font="TkFixedFont")
        self.lst_nodes.configure(takefocus="cmd_lst_nodes_focus")
        self.lst_nodes.configure(width=144)
        self.lst_nodes.configure(selectmode=SINGLE)
        self.lst_nodes.configure(listvariable=duration_support.var_lst_nodes)
        self.lst_nodes.configure(exportselection=0)
        self.lst_nodes.bind('<Button1-ButtonRelease>', duration_support.on_lst_nodes_select)

        self.lst_risks = ttk.Combobox(top)
        self.lst_risks.place(relx=0.08, rely=0.07, relheight=0.04, relwidth=0.19)

        # self.value_list = [1,2,3,]
        # self.lst_risks.configure(values=self.value_list)
        self.lst_risks.configure(textvariable=duration_support.var_lst_risks)
        self.lst_risks.configure(width=147)
        self.lst_risks.configure(takefocus="cmd_lst_risks_focus")
        self.lst_risks.bind(" <<ComboboxSelected>>", duration_support.on_lst_risks_select)

        self.style.configure('TNotebook.Tab', background=self._bgcolor)
        self.style.configure('TNotebook.Tab', foreground=self._fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', self._compcolor), ('active',self._ana2color)])
        self.TNotebook1 = ttk.Notebook(top)
        self.TNotebook1.place(relx=0.29, rely=0.07, relheight=0.81
                , relwidth=0.69)
        self.TNotebook1.configure(width=542)
        self.TNotebook1.configure(takefocus="cmd_data_focus")
        self.TNotebook1_pg0 = ttk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_pg0, padding=3)
        self.TNotebook1.tab(0, text="Choices",underline="-1",)
        self.TNotebook1_pg1 = ttk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_pg1, padding=3)
        self.TNotebook1.tab(1, text="Choices Table",underline="-1",)

        self.Label3 = Label(self.TNotebook1_pg0)
        self.Label3.place(relx=0.04, rely=0.03, height=18, width=87)
        self.Label3.configure(text='''Enter Choices''')

        self.txt_labels = Text(self.TNotebook1_pg0)
        self.txt_labels.place(relx=0.04, rely=0.1, relheight=0.78, relwidth=0.94)
        self.txt_labels.configure(background="white")
        self.txt_labels.configure(font="TkTextFont")
        self.txt_labels.configure(selectbackground="#c4c4c4")
        self.txt_labels.configure(width=506)
        self.txt_labels.configure(wrap=WORD)

        self.btn_choices_apply = Button(self.TNotebook1_pg0)
        self.btn_choices_apply.place(relx=0.83, rely=0.9, height=26, width=77)
        self.btn_choices_apply.configure(activebackground="#d9d9d9")
        self.btn_choices_apply.configure(command=duration_support.cmd_choices_apply)
        self.btn_choices_apply.configure(text='''Apply''')
        self.btn_choices_apply.configure(width=77)

        self.Label4 = Label(self.TNotebook1_pg1)
        self.Label4.place(relx=0.04, rely=0.03, height=18, width=68)
        self.Label4.configure(text='''Enter data''')

        self.frm_data = Frame(self.TNotebook1_pg1)
        self.frm_data.place(relx=0.04, rely=0.1, relheight=0.79, relwidth=0.94)
        self.frm_data.configure(relief=GROOVE)
        self.frm_data.configure(borderwidth="2")
        self.frm_data.configure(relief=GROOVE)
        self.frm_data.configure(width=505)

        self.btn_data_apply = Button(self.TNotebook1_pg1)
        self.btn_data_apply.place(relx=0.83, rely=0.9, height=26, width=77)
        self.btn_data_apply.configure(activebackground="#d9d9d9")
        self.btn_data_apply.configure(command=duration_support.cmd_data_apply)
        self.btn_data_apply.configure(text='''Apply''')
        self.btn_data_apply.configure(width=77)

        self.Label1 = Label(top)
        self.Label1.place(relx=0.01, rely=0.07, height=18, width=34)
        self.Label1.configure(text='''Risks''')

        self.Label2 = Label(top)
        self.Label2.place(relx=0.01, rely=0.15, height=18, width=44)
        self.Label2.configure(text='''Nodes''')

        self.btn_cancel = Button(top)
        self.btn_cancel.place(relx=0.9, rely=0.92, height=26, width=67)
        self.btn_cancel.configure(activebackground="#d9d9d9")
        self.btn_cancel.configure(command=duration_support.cmd_quit)
        self.btn_cancel.configure(text='''Cancel''')

        self.btn_apply = Button(top)
        self.btn_apply.place(relx=0.8, rely=0.92, height=26, width=67)
        self.btn_apply.configure(activebackground="#d9d9d9")
        self.btn_apply.configure(command=duration_support.cmd_apply)
        self.btn_apply.configure(text='''Apply''')

        self.btn_ok = Button(top)
        self.btn_ok.place(relx=0.71, rely=0.92, height=26, width=67)
        self.btn_ok.configure(activebackground="#d9d9d9")
        self.btn_ok.configure(command=duration_support.cmd_ok)
        self.btn_ok.configure(text='''OK''')

        self.btn_help = Button(top)
        self.btn_help.place(relx=0.01, rely=0.92, height=26, width=67)
        self.btn_help.configure(activebackground="#d9d9d9")
        self.btn_help.configure(command=duration_support.cmd_help)
        self.btn_help.configure(text='''Help''')

        self.msg_notif = Message(top)
        self.msg_notif.place(relx=0.11, rely=0.93, relheight=0.05, relwidth=0.58)

        self.msg_notif.configure(foreground="#eb0018")
        self.msg_notif.configure(text='''Message''')
        self.msg_notif.configure(textvariable=duration_support.var_notif)
        self.msg_notif.configure(width=453)






if __name__ == '__main__':
    vp_start_gui()
